version: 2
jobs:
  build:
    branches:
      ignore:
        - xx
    docker:
      - image: circleci/node:8-stretch-browsers-legacy
    steps:
      - run:
          name: install_npm
          command: sudo npm install -g npm
      - run:
          name: list
          command: pwd; ls -ltra
      - run:
          name: npm_install_packages
          command: npm install
      - run:
          name: run_tests
          command: npm run test