version: 2
jobs:
  build:
    branches:
      ignore:
        - xx
    docker:
      - image: circleci/node:8-stretch-browsers-legacy
    steps:
      - run:
          name: install_npm
          command: sudo npm install -g npm
      - run:
          name: npm_install_packages
          command: cd nephridium; npm install
      - run:
          name: run_tests
          command: cd nephridium; npm run test